version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/anyhow
    exclude:
      - appspec.yml
      - afterinstall.sh

hooks:
  BeforeInstall:  # Replace the existing files before the installation script runs
    - location: /rscripts/auth.json.sample.replace.sh
      runAs: root

  AfterInstall:
    - location: /afterinstall.sh
      runAs: root

artifacts:
  files:
    - '**/*'  # Include all files in the build output
  discard-paths: no

